import { Agent, ActivityEntry } from './types';

export const agents: Agent[] = [
  {
    id: 'lead-scraper',
    name: 'LEAD SCRAPER',
    description: 'Scrapes LinkedIn and Twitter for prospects matching ICP criteria',
    status: 'active',
    category: 'outreach',
    connectedTo: ['cold-emailer'],
    config: {
      schedule: 'Every 6h',
      api: 'LinkedIn API, Twitter API',
      prompt: 'Find founders and COOs at service businesses doing $1M-$10M ARR who post about AI automation or operations bottlenecks.',
    },
    stats: { runs: 1847, lastRun: '2 min ago', avgDuration: '4.2s' },
  },
  {
    id: 'cold-emailer',
    name: 'COLD EMAILER',
    description: 'Generates and sends personalized cold outreach sequences',
    status: 'active',
    category: 'outreach',
    connectedTo: ['lead-scorer'],
    config: {
      schedule: 'Every 4h',
      api: 'Instantly API',
      prompt: 'Write a 3-email sequence. Tone: direct, no fluff. Reference their recent post or company milestone. CTA: 15-min call.',
    },
    stats: { runs: 923, lastRun: '18 min ago', avgDuration: '1.8s' },
  },
  {
    id: 'lead-scorer',
    name: 'LEAD SCORER',
    description: 'Scores inbound and outbound leads based on engagement signals',
    status: 'idle',
    category: 'ops',
    connectedTo: [],
    config: {
      schedule: 'Every 1h',
      api: 'Internal',
      prompt: 'Score leads 1-100 based on: email opens, link clicks, reply sentiment, company size, and ICP match.',
    },
    stats: { runs: 4102, lastRun: '47 min ago', avgDuration: '0.3s' },
  },
  {
    id: 'ad-builder',
    name: 'AD BUILDER',
    description: 'Generates ad creative variants for Meta campaigns',
    status: 'active',
    category: 'ads',
    brand: 'Arc Ads',
    connectedTo: ['ad-auditor'],
    config: {
      schedule: 'On demand',
      api: 'Arc Ads API, OpenAI API',
      prompt: 'Generate 3 ad variants per campaign. Hook-first copy. Test: image vs. video. Keep under 125 chars primary text.',
    },
    stats: { runs: 312, lastRun: '1h ago', avgDuration: '12.1s' },
  },
  {
    id: 'ad-auditor',
    name: 'AD AUDITOR',
    description: 'Monitors ad performance and kills underperformers',
    status: 'active',
    category: 'ads',
    connectedTo: ['ad-builder'],
    config: {
      schedule: 'Every 2h',
      api: 'Meta Ads API',
      prompt: 'Review all active ads. Kill anything under 1.5x ROAS after $50 spend. Scale winners by 20%. Flag creative fatigue above 3.0 frequency.',
    },
    stats: { runs: 1561, lastRun: '35 min ago', avgDuration: '2.4s' },
  },
  {
    id: 'content-repurposer',
    name: 'CONTENT REPURPOSER',
    description: 'Takes long-form content and splits into platform-specific posts',
    status: 'idle',
    category: 'content',
    connectedTo: ['content-scheduler'],
    config: {
      schedule: 'Daily 6am',
      api: 'OpenAI API',
      prompt: 'Take YouTube transcript. Output: 1 LinkedIn post (professional, data-driven), 3 Twitter posts (punchy, thread-ready), 1 IG caption (casual, CTA to link in bio).',
    },
    stats: { runs: 89, lastRun: '14h ago', avgDuration: '8.7s' },
  },
  {
    id: 'content-scheduler',
    name: 'CONTENT SCHEDULER',
    description: 'Queues and publishes content across platforms on schedule',
    status: 'idle',
    category: 'content',
    connectedTo: [],
    config: {
      schedule: 'Continuous',
      api: 'Buffer API, Twitter API, LinkedIn API',
      prompt: 'Post LinkedIn at 8am EST Tue/Thu. Twitter 3x daily. IG stories at noon. Never double-post within 2h.',
    },
    stats: { runs: 241, lastRun: '6h ago', avgDuration: '1.1s' },
  },
  {
    id: 'brand-scout',
    name: 'BRAND SCOUT',
    description: 'Identifies potential brand deal partners based on niche fit',
    status: 'active',
    category: 'research',
    connectedTo: ['deal-pitcher'],
    config: {
      schedule: 'Every 12h',
      api: 'Internal, Web scraping',
      prompt: 'Find AI/SaaS tools with affiliate or sponsorship programs. Filter: must have API, must be relevant to automation/AI audience, min $500 CPM or $200 flat.',
    },
    stats: { runs: 156, lastRun: '3h ago', avgDuration: '22.3s' },
  },
  {
    id: 'deal-pitcher',
    name: 'DEAL PITCHER',
    description: 'Drafts outreach emails to potential brand partners',
    status: 'idle',
    category: 'research',
    connectedTo: [],
    config: {
      schedule: 'On demand',
      api: 'Gmail API',
      prompt: 'Draft a pitch email. Lead with audience stats (245k followers, 5.4% engagement). Propose integration format: "I build an agent using your API on camera." Include rate card.',
    },
    stats: { runs: 43, lastRun: '2d ago', avgDuration: '3.1s' },
  },
];

export const activityFeed: ActivityEntry[] = [
  { id: '1', agentId: 'lead-scraper', agentName: 'LEAD SCRAPER', action: 'Scraped 47 prospects from LinkedIn Sales Navigator', timestamp: '14:32:01' },
  { id: '2', agentId: 'cold-emailer', agentName: 'COLD EMAILER', action: 'Sent sequence to 12 new leads — batch #923', timestamp: '14:28:44' },
  { id: '3', agentId: 'ad-auditor', agentName: 'AD AUDITOR', action: 'Killed ad set "Agency_V3_Retarget" — ROAS 0.8x after $62 spend', timestamp: '14:15:22' },
  { id: '4', agentId: 'ad-builder', agentName: 'AD BUILDER', action: 'Generated 3 variants for campaign "Q1_Founders"', timestamp: '14:12:09' },
  { id: '5', agentId: 'brand-scout', agentName: 'BRAND SCOUT', action: 'Found 4 new potential partners: Relevance AI, Bland AI, Voiceflow, Make', timestamp: '13:58:33' },
  { id: '6', agentId: 'ad-auditor', agentName: 'AD AUDITOR', action: 'Scaled "Agency_V2_Cold" by 20% — ROAS 4.1x', timestamp: '13:45:11' },
  { id: '7', agentId: 'lead-scorer', agentName: 'LEAD SCORER', action: 'Scored 89 leads — 12 flagged as hot (score >80)', timestamp: '13:31:00' },
  { id: '8', agentId: 'cold-emailer', agentName: 'COLD EMAILER', action: '3 replies detected — 2 positive, 1 objection', timestamp: '13:22:17' },
  { id: '9', agentId: 'content-repurposer', agentName: 'CONTENT REPURPOSER', action: 'Split "Claude Code Deep Dive" into 5 posts across 3 platforms', timestamp: '06:00:44' },
  { id: '10', agentId: 'content-scheduler', agentName: 'CONTENT SCHEDULER', action: 'Published LinkedIn post — "Why your AI assistant is a security risk"', timestamp: '08:01:02' },
  { id: '11', agentId: 'lead-scraper', agentName: 'LEAD SCRAPER', action: 'Scraped 31 prospects from Twitter — keyword: "n8n automation"', timestamp: '08:32:01' },
  { id: '12', agentId: 'ad-builder', agentName: 'AD BUILDER', action: 'New creative batch ready — 3 static, 1 video variant', timestamp: '09:44:55' },
  { id: '13', agentId: 'brand-scout', agentName: 'BRAND SCOUT', action: 'Flagged Wispr Flow — strong API, AI audience overlap, $800 flat offer', timestamp: '01:58:12' },
  { id: '14', agentId: 'deal-pitcher', agentName: 'DEAL PITCHER', action: 'Drafted pitch to Relevance AI — awaiting review', timestamp: '10:15:30' },
  { id: '15', agentId: 'ad-auditor', agentName: 'AD AUDITOR', action: 'Creative fatigue alert: "Agency_V1_Broad" freq 3.4 — paused', timestamp: '11:02:48' },
];
